#!/usr/bin/bash

device="20:91:DF:4C:78:73"

/usr/bin/expect -f - <<EOF
set timeout 60
spawn bluetoothctl
send -- "scan on\r"
expect "$device"
send -- "connect $device\r"
expect "Connection successful"
send -- "trust $device\r"
expect "trust succeeded"
send -- "exit\r"
expect eof
EOF

sleep 1

xinput set-prop "Apple Inc. Magic Trackpad 2" "libinput Tapping Enabled" 1
xinput set-prop "Apple Inc. Magic Trackpad 2" "libinput Accel Speed" 0.15
